---
- name: elk installer
  hosts: elkservers
  remote_user: berlys
  become: true
  tasks:
  - name: increase memory
    shell: sysctl -w vm.max_map_count=262144
  - name: docker.io
    apt:
      force_apt_get: yes
      name: docker.io
      state: present
  - name: pipper
    apt:
      force_apt_get: yes
      name: python-pip
      state: present
  - name: docker python
    pip:
      name: docker
      state: present
  - name: create container
    docker_container:
        name: elk
        image: sebp/elk
        state: started
        published_ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044
